#!/bin/sh

. alba_blissrc

cd /usr/share/tangods-pystatecomposer/PyStateComposer/
script /dev/null
# Or just run sudo -u bob script -q -c 'screen -dr myscreen' /dev/null
screen -dm -S PyStateComposer-$1 python PyStateComposer.py $1 $2

